### ISSUE TITLE
Send Code suddenly not working

### ISSUE THREAD

**Issue by ECon87** [randy3k/SendCode#120]
Hi,

I am using Sublime Text 3 on a Mac and SendCode seems to have suddenly stopped working. The command palette  seems to work fine, but when I click on "SendCode: Choose Program" nothing happens. It was working fine 2 hours ago.

I uninstalled and re-installed sendcode but nothing changed.

Does anyone else have similar problems?

**Comment by randy3k** [comment]
We have just published a new release, is there any error in the console? Did you try restarting Sublime Text?

**Comment by ECon87** [comment]
I restarted Sublime but it did nothing.

I got this error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/Users/EvangelosConstantinou/Library/Application Support/Sublime Text 3/Packages/SendCode/choose_prog.py", line 51, in run
    prog = settings.get("prog")
  File "/Users/EvangelosConstantinou/Library/Application Support/Sublime Text 3/Packages/SendCode/settings.py", line 39, in get
    project_settings = window.project_data().get("settings", {}).get("SendCode", {})
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by randy3k** [comment]
Thank for the report. v0.4.16 has fixed it.
