### ISSUE TITLE
sendcode suddenly not working 

### ISSUE THREAD

**Issue by vkc102** [randy3k/SendCode#121]
Hi, 
Sendcode is amazing and I've been using it for some time now in my coding workflows. But recently it has stopped working when trying to send code to either terminus, SublmeREPL or linux-term. The sublime console outputs 
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/home/vkc102/.config/sublime-text-3/Packages/SendCode/send_code.py", line 81, in run
    sender = CodeSender.initialize(self.view, prog=prog, from_view=cmd is None)
  File "/home/vkc102/.config/sublime-text-3/Packages/SendCode/code_sender/sender.py", line 35, in initialize
    syntax = Settings(view).syntax()
  File "/home/vkc102/.config/sublime-text-3/Packages/SendCode/settings.py", line 15, in __init__
    self.s = sublime.load_settings("SendCode.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
```
I am running Sublime Text 3.2.2 (build 3211) and I think the issue began after that upgrade. But  I am not sure based on the ST3 change log. Any help would be appreciated. 

Best,

Victor

**Comment by randy3k** [comment]
Try restarting it

**Comment by vkc102** [comment]
Thanks!!! Restarting my machine, Linux kernel and all worked.

Also why does it do this sometimes? I often put my machine to sleep, but it has never  been an issue before.
