### ISSUE TITLE
SendCode: argument `cmd` is deprecated, use `code` instead

### ISSUE THREAD

**Issue by glaucocustodio** [randy3k/SendCode#159]
Just updated to ST 4121 and started seeing this error: 

```
SendCode: argument `cmd` is deprecated, use `code` instead.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
  File "/Users/my_user/Library/Application Support/Sublime Text/Packages/SendCode/send_code.py", line 22, in run
    getter = CodeGetter.initialize(self.view)
  File "/Users/my_user/Library/Application Support/Sublime Text/Packages/SendCode/code_getter/getter.py", line 19, in initialize
    PATTERN = re.compile(r"""
  File "/Users/my_user/Library/Application Support/Sublime Text/Packages/SendCode/settings.py", line 15, in __init__
    self.s = sublime.load_settings("SendCode.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by randy3k** [comment]
Please restart sublime and try again.
Similar issues
https://github.com/randy3k/SendCode/issues/157
https://github.com/randy3k/SendCode/issues/158

**Comment by glaucocustodio** [comment]
working now, thanks.
