### ISSUE TITLE
Sendcode not working with gnome-terminal on Ubuntu

### ISSUE THREAD

**Issue by gautam-sabnis** [randy3k/SendCode#166]
Hi. I am having trouble making sendcode work on Ubuntu. I have already installed `xdotool`. 
In the `config` file, I tried both `"linux_terminal": "gnome-terminal-server"` and `"linux_terminal": "Gnome-terminal"`. 

I get the following error in the `console` - 

> Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1451, in run_
    return self.run(**args)
  File "/opt/sublime_text/Packages/Default.sublime-package/settings.py", line 122, in run
AttributeError: 'NoneType' object has no attribute 'replace'
Unable to open /home/user/.config/sublime-text/Packages/User/SendCode.sublime-settings
Traceback (most recent call last):
  File "/home/user/.config/sublime-text/Packages/SendCode/send_code.py", line 29, in <lambda>
    sublime.set_timeout_async(lambda: sender.send_text(code))
  File "/home/user/.config/sublime-text/Packages/SendCode/code_sender/sender.py", line 94, in send_text
    self.send_to_terminal(cmd)
  File "/home/user/.config/sublime-text/Packages/SendCode/code_sender/sender.py", line 167, in send_to_terminal
    send_to_terminal(cmd)
  File "/home/user/.config/sublime-text/Packages/SendCode/code_sender/terminal/__init__.py", line 12, in send_to_terminal
    osascript(TERMINAL, cmd)
  File "/home/user/.config/sublime-text/Packages/SendCode/code_sender/applescript.py", line 5, in osascript
    subprocess.check_call(["osascript"] + list(args))
  File "./python3.3/subprocess.py", line 542, in check_call
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'osascript'

What am I missing? Thanks!

**Comment by randy3k** [comment]
For some reason, the trace back suggested that you are using a Mac and sending code via AppleScript. Could you confirm that you have selected the correct program to send to?

**Comment by gautam-sabnis** [comment]
Thanks for the response. Strange that it says I am using a Mac! I am on Ubuntu and sending the code to the gnome-terminal. I changed `prog` in `send code settings` from `terminal to tmux,` and it worked. It can only send code to tmux and not otherwise. Is there a way to get it working purely in the terminal?
