### ISSUE TITLE
[Bug] FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by Kristinita** [randy3k/SendCode#19]
### Summary

I can not begin to use SendREPL.

### Expected behavior

Successful begin to use SendREPL.

### Actual behavior

For ConEmu:

```python
key evt: control+f1
command: send_repl
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 74, in send_text
    self.send_to_conemu(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 46, in send_to_conemu
    send_to_conemu(cmd, self.bracketed_paste_mode)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\conemu\__init__.py", line 51, in send_to_conemu
    ret = subprocess.call("ConEmuC /ConInfo", startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

For SublimeREPL:

```python
key evt: control+f1
command: send_repl
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "E:\Sublime Text 3\Data\Packages\SublimeREPL\text_transfer.py", line 141, in run
    for rv in manager.find_repl(external_id):
  File "E:\Sublime Text 3\Data\Packages\SublimeREPL\sublimerepl.py", line 470, in find_repl
    if not (rv.repl and rv.repl.is_alive()):
  File "E:\Sublime Text 3\Data\Packages\SublimeREPL\repls\subprocess_repl.py", line 209, in is_alive
    return self.popen.poll() is None
  File "./python3.3/subprocess.py", line 930, in poll
  File "./python3.3/subprocess.py", line 1145, in _internal_poll
OSError: [WinError 6] Неверный дескриптор
```

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I have ConEmu in `C:\Program Files\ConEmu` folder. I install SendREPL via Package Control → I add in my `User/Default (Windows).sublime-keymap` these lines:

```json
// SendREPL
{
    "keys": ["ctrl+f1"],
    "command": "send_repl",
    "context": [{
        "key": "selector",
        "operator": "equal",
        "operand": "source"
    }]
}, {
    "keys": ["ctrl+f1"],
    "command": "send_repl",
    "context": [{
        "key": "selector",
        "operator": "equal",
        "operand": "text.html.markdown.gfm"
    }]
},
```

<kbd>Ctrl+Shift+P</kbd> → `SendREPL: Choose REPL Program` → I select `ConEmu` in Quick Panel:

![ConEmu](http://i.imgur.com/En298Iu.png)

I restart Sublime Text → I select, for example, `python --version` in `.md` file with Markdown GFM syntax → I press <kbd>Ctrl+F1</kbd> → I get stack trace in console.

Maybe I need wrote ConEmu path in SendREPL settings, but I can not find, how I can do it.

<kbd>Ctrl+Shift+P</kbd> → `SendREPL: Choose REPL Program` → I select `Cmder` in Quick Panel → I select, for example, `python --version` in `.md` file with Markdown GFM syntax → I press <kbd>Ctrl+F1</kbd> → I get same stack trace in console like ConEmu.

<kbd>Ctrl+Shift+P</kbd> → `SendREPL: Choose REPL Program` → I select `SublimeREPL` in Quick Panel → I select, for example, `python --version` in `.md` file with Markdown GFM syntax → I press <kbd>Ctrl+F1</kbd> → I get stack trace.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126
**ConEmu:**
16.10.22.0

Thanks.

**Comment by randy3k** [comment]
You might need to modify the `PATH` environment variable to include the path to `ConEmuC.exe`, [see here on how to][1].

For the other issue, you should contact [SublimeREPL][2], it is mostly because you haven't opened a python console.

[1]: http://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10
[2]: https://github.com/wuub/SublimeREPL

**Comment by Kristinita** [comment]
1. I already try modify `PATH` environment variable o include the path to `ConEmuC.exe`:

![ConEmuC](http://i.imgur.com/Ke9xeoQ.png)

If I run command `ConEmuC /ConInfo` in terminal:

```shell
λ ConEmuC /ConInfo
ConEmu 160710 x86
OS Version: 10.0.14393 (2:)
SM_IMMENABLED=1, SM_DBCSENABLED=0, ACP=1251, OEMCP=866
ConHWND=0x00040998, Class="ConsoleWindowClass"
Console font info: 0, {3x5}, 54, 400, "Lucida Console"
Handles: In=x8 (Mode=x1F7) Out=xC (x3) Err=x10 (x3)
Buffer={67,1000} Window={0,0}-{66,21} MaxSize={67,190}
Cursor: Pos={0,9} Size=25% Visible
ConsoleCP=866, ConsoleOutputCP=866
CP866: Max=1 Def=x3F,x00 UDef=x3F
  Lead=x00,x00,x00,x00,x00,x00,x00,x00,x00,x00,x00,x00
  Name="866   (OEM - русская)"
```

But if I select text in my Sublime Text tab and press Ctrl+F1, I get stack trace:

```python
command: send_repl
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 74, in send_text
    self.send_to_conemu(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 46, in send_to_conemu
    send_to_conemu(cmd, self.bracketed_paste_mode)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\conemu\__init__.py", line 51, in send_to_conemu
    ret = subprocess.call("ConEmuC /ConInfo", startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

---

---

2.
+ What is «python console»? <kbd>Ctrl+Shift+P</kbd> → `SublimeREPL: Python` console is worked for me.
+ In SublimeREPL long time no update, almost useless to write to the developer of SublimeREPL.

**Comment by randy3k** [comment]
Are you using Cmder or ConEmu? For Cmder, the binary should be under the directory `vendor\conemu-maximus5\conemu`

Can you try the follwing in the sublime console

```
import subprocess; subprocess.call("ConEmuC /ConInfo", startupinfo=startupinfo)
```

**Comment by Kristinita** [comment]
@randy3k , I use and select ConEmu.

```python
>>> import subprocess; subprocess.call("ConEmuC /ConInfo", startupinfo=startupinfo)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'startupinfo' is not defined
```

Thanks.

**Comment by randy3k** [comment]
Oh, I am sorry, it should be 

```python
import subprocess; subprocess.call("ConEmuC /ConInfo")
```

**Comment by Kristinita** [comment]
```python
>>> import subprocess; subprocess.call("ConEmuC /ConInfo")
0
```

And new small window open for me and quickly (less than a second) close.

Thanks.

**Comment by randy3k** [comment]
Are you running the code in Sublime console (triggered by <kbd>ctrl + `</kbd>)?
If you are, it seems that Sublime could locate ConEmuC. How about this?

```
import subprocess; subprocess.check_output("ConEmuC /ConInfo")
```

PS: The small window is expected.

**Comment by Kristinita** [comment]
> Are you running the code in Sublime console (triggered by ctrl + `)?

Yes.

```python
>>> import subprocess; subprocess.check_output("ConEmuC /ConInfo")
b''
```

And small window was shown for me again.

Thanks.

**Comment by randy3k** [comment]
it means Sublime finds ConEmuC, could you try using SendREPL again to see if the problem persists?


If it still doesn't work, try registering the ConEmu Here context menu.

![screen shot 2016-11-17 at 2 22 00 pm](https://cloud.githubusercontent.com/assets/1690993/20404060/4b59253e-acd1-11e6-898c-99af253863b4.png)

**Comment by randy3k** [comment]
I have just released `v0.1.7`, hope it will help.

**Comment by Kristinita** [comment]
Now I get stack trace:

```python
key evt: control+f1
command: send_repl
ConEmuC.exe not found. Edit PATH variable and add path to ConEmuC.exe.
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 81, in send_text
    self.send_to_conemu(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 47, in send_to_conemu
    send_to_conemu(cmd, conemuc, self.bracketed_paste_mode)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\conemu\__init__.py", line 66, in send_to_conemu
    _send_to_conemu(cmd, conemuc, bracketed)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\conemu\__init__.py", line 91, in _send_to_conemu
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 547, in check_call
subprocess.CalledProcessError: Command 'ConEmuC -GuiMacro:0 Paste(2,"python --version")' returned non-zero exit status 134
```

But I have path to ConEmuC.exe in my PATH variable:

![ConEmuC path](https://camo.githubusercontent.com/54d55ae3e2536bbc5263f49e8d4c33b0212ae3cb/687474703a2f2f692e696d6775722e636f6d2f4b653978656f512e706e67)

My ConEmu settings:

![ConEmu Settings](http://i.imgur.com/G28sXAH.png)

Thanks.

**Comment by randy3k** [comment]
Did you figure it out? If you still have an issue, try to specify the [path][1] to `ComEmuC.exe`.

[1]: https://github.com/randy3k/SendREPL/blob/4525872708c9aac789ec42eca4fa7458dcdec07c/SendREPL%20(Windows).sublime-settings#L37

**Comment by randy3k** [comment]
Oops, I just caught a bug of the path specification in v0.1.8. Please use version v0.1.9.

**Comment by Kristinita** [comment]
@randy3k, now if ConEmu open for me, I select my command → <kbd>Ctrl+F1</kbd> → command run in ConEmu.

But if ConEmu not open for me for me, I select my command → <kbd>Ctrl+F1</kbd> → I get stack trace:

```python
key evt: control+f1
command: send_repl
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\send_repl.py", line 67, in run
    sender.send_text(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 81, in send_text
    self.send_to_conemu(cmd)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\text_sender.py", line 47, in send_to_conemu
    send_to_conemu(cmd, conemuc, bracketed=self.bracketed_paste_mode)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\conemu\__init__.py", line 66, in send_to_conemu
    _send_to_conemu(cmd, conemuc, bracketed)
  File "E:\Sublime Text 3\Data\Packages\SendREPL\conemu\__init__.py", line 93, in _send_to_conemu
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 547, in check_call
subprocess.CalledProcessError: Command 'ConEmuC -GuiMacro:0 Paste(2,"stack trace")' returned non-zero exit status 134
```

Thanks.

**Comment by randy3k** [comment]
You need to first open conemu in the current implementation. It could be a feature request to open the console autonatically

**Comment by Kristinita** [comment]
@randy3k , feature request in SendREPL?

Thanks.

**Comment by bosbyj** [comment]
Same error meets me. Sublime console says,
"ConEmuC.exe not found. Specify the path to ConEmuC.exe in SendREPL.sublime-settings."

But I am sure that I have set the path correctly and ConEmuC could run under plain cmd.exe

========
Cmder 1.3.2
ST 3126

**Comment by randy3k** [comment]
This issue has been a while, so I am going to close it. If you still face the same issue, feel free to re-open it or open a new issue.
