### ISSUE TITLE
Sending to R Console fails

### ISSUE THREAD

**Issue by Superstud** [randy3k/SendCode#54]
Hi,

I restarted Sublime Text and I assume that SendCode was updated because it now fails to send code to the R Console. Output in console:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "C:\Users\alo\AppData\Roaming\Sublime Text 3\Packages\SendCode\send_code.py", line 72, in run
    sender = TextSender.initialize(self.view, prog=prog)
  File "C:\Users\alo\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_sender\sender.py", line 31, in initialize
    syntax = Settings(view).syntax()
  File "C:\Users\alo\AppData\Roaming\Sublime Text 3\Packages\SendCode\settings.py", line 58, in __init__
    self.s = sublime.load_settings("SendCode.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by randy3k** [comment]
It seems a Sublime Text issue. Would you try to restart again?

**Comment by Superstud** [comment]
That worked - thanks! :-)

**Comment by randy3k** [comment]
Great.
