### ISSUE TITLE
rstudio not found

### ISSUE THREAD

**Issue by faridcher** [randy3k/SendCode#64]
While I have Rstudio opened, I get the following error when trying to `send_code` to its consolse:

> Traceback (most recent call last):
  File "C:\Users\farid\AppData\Roaming\Sublime Text 3\Packages\SendCode\send_code.py", line 79, in <lambda>
    sublime.set_timeout_async(lambda: sender.send_text(cmd))
  File "C:\Users\farid\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_sender\sender.py", line 131, in send_text
    super(RTextSender, self).send_text(cmd)
  File "C:\Users\farid\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_sender\sender.py", line 113, in send_text
    self.send_to_rstudio(cmd)
  File "C:\Users\farid\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_sender\sender.py", line 82, in send_to_rstudio
    send_to_rstudio(cmd, from_view=self.from_view)
  File "C:\Users\farid\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_sender\rstudio\__init__.py", line 19, in send_to_rstudio
    rid = winauto.find_rstudio()
  File "C:\Users\farid\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_sender\winauto.py", line 161, in find_rstudio
    raise Exception("rstudio not found.")
Exception: rstudio not found.

**Comment by randy3k** [comment]
I just discovered that it does not work if a Project is being opened in RStudio. It only works with a plain RStudio window. Will fix soon.

**Comment by randy3k** [comment]
686d40f87074e22efafe5954768401b6844a7544 should fix it.

**Comment by faridcher** [comment]
that worked. 
thanks

**Comment by randy3k** [comment]
Great.
