### ISSUE TITLE
Ctrl+Enter: AttributeError: 'NoneType' object has no attribute 'load_settings'

### ISSUE THREAD

**Issue by taqtiqa-mark** [randy3k/SendCode#67]
**ST3 build 3144 64 bit**
SendCode master  **7c8a27b **

**Platform:**
Ubuntu Xenial 16.04 64 bit

**Action:**
Start ST3
Start tmux
Start R console
Open R-file
ctrl+enter

**Result**
````
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/home/hedge/.config/sublime-text-3/Packages/SendCode/send_code.py", line 81, in run
    sender = CodeSender.initialize(self.view, prog=prog, from_view=cmd is None)
  File "/home/hedge/.config/sublime-text-3/Packages/SendCode/code_sender/sender.py", line 32, in initialize
    syntax = Settings(view).syntax()
  File "/home/hedge/.config/sublime-text-3/Packages/SendCode/settings.py", line 58, in __init__
    self.s = sublime.load_settings("SendCode.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
````

**Notes**
To check SendCode settings `References>Package settings>SendCode> Settings`
````
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "settings in /opt/sublime_text/Packages/Default.sublime-package", line 101, in run
AttributeError: 'NoneType' object has no attribute 'replace'
````

**Comment by randy3k** [comment]
It is likely a sublime text issue. A restart should fix the problem.

**Comment by taqtiqa-mark** [comment]
Thanks again for the prompt response.  Will try restarting tonight.

**Comment by taqtiqa-mark** [comment]
Closing. Will reopen if ST3 restart does not resolve the issue.
