### ISSUE TITLE
Still unable to "send  code" to iterm-2 (macosx)

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#72]
This was temporarily solved, seems to have broken with upgrade to iterm2.  Frustrating that this keeps  breaking, as  its essential to my workflow.

**Comment by randy3k** [comment]
I really have no idea why it happens to you. It is working perfectly on my side..

**Comment by adamaltmejd** [comment]
Just started failing for me too. Worked just a few days ago. Tried to switch to different terminal and it doesn't help. I get this error message:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "~/Library/Application Support/Sublime Text 3/Packages/SendCode/send_code.py", line 81, in run
    sender = CodeSender.initialize(self.view, prog=prog, from_view=cmd is None)
  File "~/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/sender.py", line 32, in initialize
    syntax = Settings(view).syntax()
  File "~/Library/Application Support/Sublime Text 3/Packages/SendCode/settings.py", line 58, in __init__
    else:
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by adamaltmejd** [comment]
Nvm, reinstalled the package and now its working.

**Comment by bitworm** [comment]
My system recognizes the command `iterm-2` instead of `iterm`.  Changing the name of the application in the applescripts in `/Users/user/Library/Application Support/Sublime Text 3/Packages/SendCode/code_sender/*.applescript` seems to have solved my problem.  Maybe this will be an issue for other users...

**Comment by randy3k** [comment]
Per iTerm2 documentation https://www.iterm2.com/documentation-scripting.html it should really be iTerm2. I will make the change soon. Thanks for the information.

**Comment by bitworm** [comment]
This breaks my sendcode every update.

**Comment by randy3k** [comment]
Could you elaborate?

**Comment by randy3k** [comment]
Oh, I just realized that I haven’t changed the application name to iTerm2

**Comment by randy3k** [comment]
@bitworm check  069437c.

**Comment by randy3k** [comment]
My computer recognizes both iTerm2 and iTerm....may be you are the oddity :-p

**Comment by 13am** [comment]
FWIW, https://github.com/randy3k/SendCode/commit/069437c4b959532426f39a35adbdd13b0acd79f9
broke SendCode for me, I'm running the newest MacOS, SublimeText, and SendCode. I had to chage iTerm2 to iTerm to make it work. Could this be made into a config option so that I'd not have to mess with the applescript manually?
