### ISSUE TITLE
ConEmu returned non-zero exit status 134

### ISSUE THREAD

**Issue by WolfDan** [randy3k/SendCode#76]
I just installed SendCode in SublimeText, I've set the path in settings but I have this error when I press `ctrl + enter`

```
Traceback (most recent call last):
  File "C:\Users\dragu\AppData\Roaming\Sublime Text 3\Packages\SendCode\send_code.py", line 88, in <lambda>
    sublime.set_timeout_async(lambda: sender.send_text(cmd))
  File "C:\Users\dragu\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\sender.py", line 95, in send_text
    self.send_to_cmder(cmd)
  File "C:\Users\dragu\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\sender.py", line 54, in send_to_cmder
    send_to_cmder(cmd, conemuc, bracketed=self.bracketed_paste_mode)
  File "C:\Users\dragu\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\conemu\__init__.py", line 73, in send_to_cmder
    _send_to_conemu(cmd, conemuc, bracketed)
  File "C:\Users\dragu\AppData\Roaming\Sublime Text 3\Packages\SendCode\code_sender\conemu\__init__.py", line 93, in _send_to_conemu
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 547, in check_call
subprocess.CalledProcessError: Command 'C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu\ConEmuC64.exe -GuiMacro:0 Paste(2,"end")' returned non-zero exit status 134
```

My sublime config

```json
{
	"conemuc": "C:\\Program Files\\cmder\\vendor\\conemu-maximus5\\ConEmu\\ConEmuC64.exe",
	"prog": "cmder"
}
```

I also tried with the `ConEmuC.exe` but still not working

**Comment by randy3k** [comment]
The setting seems valid. Did you open a Cmder window as first?

**Comment by WolfDan** [comment]
No I haven't open any cmder windows

I tested with cmder opened, it don't throw any error, but it don't do anything

**Comment by randy3k** [comment]
Try switch back to `ConEmuC.exe`?

**Comment by WolfDan** [comment]
As I mentioned before, no matter if is the 64 or the 32 bits version, I still getting the same error

**Comment by randy3k** [comment]
I just confirmed that both `ConEmuC64.exe` and `ConEmuC.exe` work for me.
Make sure there is at least one Cmder window, that error message usually pops out when ConEmuC.exe cannot find any window to paste the code.

**Comment by WolfDan** [comment]
My apologies @randy3k I thought that a new terminal will be opened inside sublime, is working fine opening a cmder window, I'll close the issue, thank you for your help
